# Figures {#sec-figures}
 
```{r} 
#| label: 'set-rda-dir-figs'
#| echo: false 
#| warnings: false 
#| eval: true
figures_dir <- fs::path('C:/Users/sophie.breitbart/Documents/R_projects/stockplotr', 'figures')
``` 

```{r} 
#| label: 'fig-biomass-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'biomass_figure.rda'))

# save rda with plot-specific name
biomass_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
biomass_plot <- biomass_plot_rda$figure
biomass_cap <- biomass_plot_rda$cap
biomass_alt_text <- biomass_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-biomass'
#| echo: false 
#| warning: false 
#| fig-cap: !expr biomass_cap 
#| fig-alt: !expr biomass_alt_text
biomass_plot
``` 

```{r} 
#| label: 'fig-pop.baa-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'pop.baa_figure.rda'))

# save rda with plot-specific name
pop.baa_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
pop.baa_plot <- pop.baa_plot_rda$figure
pop.baa_cap <- pop.baa_plot_rda$cap
pop.baa_alt_text <- pop.baa_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-pop.baa'
#| echo: false 
#| warning: false 
#| fig-cap: !expr pop.baa_cap 
#| fig-alt: !expr pop.baa_alt_text
pop.baa_plot
``` 

```{r} 
#| label: 'fig-pop.caa-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'pop.caa_figure.rda'))

# save rda with plot-specific name
pop.caa_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
pop.caa_plot <- pop.caa_plot_rda$figure
pop.caa_cap <- pop.caa_plot_rda$cap
pop.caa_alt_text <- pop.caa_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-pop.caa'
#| echo: false 
#| warning: false 
#| fig-cap: !expr pop.caa_cap 
#| fig-alt: !expr pop.caa_alt_text
pop.caa_plot
``` 

```{r} 
#| label: 'fig-pop.naa-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'pop.naa_figure.rda'))

# save rda with plot-specific name
pop.naa_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
pop.naa_plot <- pop.naa_plot_rda$figure
pop.naa_cap <- pop.naa_plot_rda$cap
pop.naa_alt_text <- pop.naa_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-pop.naa'
#| echo: false 
#| warning: false 
#| fig-cap: !expr pop.naa_cap 
#| fig-alt: !expr pop.naa_alt_text
pop.naa_plot
``` 

```{r} 
#| label: 'fig-recruitment.deviations-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'recruitment.deviations_figure.rda'))

# save rda with plot-specific name
recruitment.deviations_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
recruitment.deviations_plot <- recruitment.deviations_plot_rda$figure
recruitment.deviations_cap <- recruitment.deviations_plot_rda$cap
recruitment.deviations_alt_text <- recruitment.deviations_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-recruitment.deviations'
#| echo: false 
#| warning: false 
#| fig-cap: !expr recruitment.deviations_cap 
#| fig-alt: !expr recruitment.deviations_alt_text
recruitment.deviations_plot
``` 

```{r} 
#| label: 'fig-spawning.biomass-setup'
#| echo: false 
#| warnings: false 
#| eval: true
# load rda
load(file.path(figures_dir, 'spawning.biomass_figure.rda'))

# save rda with plot-specific name
spawning.biomass_plot_rda <- rda

# remove generic rda object
rm(rda)

# save figure, caption, and alt text as separate objects
spawning.biomass_plot <- spawning.biomass_plot_rda$figure
spawning.biomass_cap <- spawning.biomass_plot_rda$cap
spawning.biomass_alt_text <- spawning.biomass_plot_rda$alt_text
``` 

```{r} 
#| label: 'fig-spawning.biomass'
#| echo: false 
#| warning: false 
#| fig-cap: !expr spawning.biomass_cap 
#| fig-alt: !expr spawning.biomass_alt_text
spawning.biomass_plot
``` 

