#' Extract data from model results to send to SIS
#'
#' Semi-automate the extraction of key quantities from model results for eventual transmittance to SIS via `asar::export_to_sis()`.
#' 
#' @param sis_data_dir Path. Location of the existing sis_assmt_template.csv and sis_ts_template.csv files, or, if absent, where new versions of the files should be saved.
#' 
#' Default: The working directory.
#' 
#' @param kq_dir Path. Location of the existing key_quantities.csv file, or, if absent, where a new version of the file should be saved.
#' 
#' Default: The working directory.
#' 
#'  
#' @details This function acts within the following workflow:
#' 
#' 1. When a stock assessment is scheduled to conclude, SIS will generate an
#'  attachment or prompt containing metadata and identifiers.
#' 2. The user will open two csv files containing placeholders for all of the data required by SIS: sis_assmt_template.csv (assessment summary data) and sis_ts_template.csv (time series data). There are three ways to obtain these files:
#' 2a. Generate the files by running `asar::create_blank_sis()`
#' 2b. Locate the files in the "report" folder generated by running `asar::create_template()`.
#' 2c. Run `stockplotr::extract_sis_data()`, which will populate the templates with data originating from a converted model results file.
#' 3. The user will add the remaining necessary data into the csv files, ensuring that all required fields are completed.
#' 4. Run `export_to_sis()`, which will format and upload this data to a specific Google Drive folder.
#' 5. The uploaded contents will be resubmitted to SIS to finalize the record.
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' extract_sis_data(
#'   sis_data_dir = getwd()
#' )
#' }
#'
extract_sis_data <- function(sis_data_dir = getwd(),
                             key_quantities_dir = getwd()
                             ) {
  # Check if existing data files exist; if not, start from blank templates
  if (!exists(fs::path(sis_data_dir, "sis_assmt_template.csv"))) {
    assmt_dat <- read.csv(fs::path("inst/resources/sis_assmt_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("No existing sis_assmt_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    assmt_dat <- read.csv(fs::path(sis_data_dir, "sis_assmt_template.csv"), stringsAsFactors = FALSE)
        cli::cli_alert_info("Found existing sis_assmt_template.csv in {sis_data_dir}.")

  }
  
  if (!exists(fs::path(sis_data_dir, "sis_ts_template.csv"))) {
    ts_dat <- read.csv(fs::path("inst/resources/sis_ts_template.csv"), stringsAsFactors = FALSE) 
    cli::cli_alert_info("No existing sis_ts_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    ts_dat <- read.csv(fs::path(sis_data_dir, "sis_ts_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("Found existing sis_ts_template.csv in {sis_data_dir}.")
  }
  
  # extract key quantities from csv and assign to variables
  # TODO: make test to check if key_quantities.csv exists; if not, ask if they want to 
  # TODO: explain which variables are from which plots
  # landings, biomass, fmort...
  # export rdas for plot_fishing_mortality() and other relevant plots
  kqs <- read.csv(fs::path(key_quantities_dir,
                           "key_quantities.csv"), 
                  stringsAsFactors = FALSE)
  
  # AS_LAST_DATA_YEAR <- kqs |>
  #   dplyr::filter(key_quantity == "landings.end.year") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_FMSY <- kqs |>
  #   dplyr::filter(key_quantity == "F.MSY.terminal") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_BMSY <- kqs |>
  #   dplyr::filter(key_quantity == "B.msy") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_BMSY_MIN <- kqs |>
  #   dplyr::filter(key_quantity == "B.msy.min") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_BMSY_MAX <- kqs |>
  #   dplyr::filter(key_quantity == "B.msy.max") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_B_YEAR <- kqs |>
  #   dplyr::filter(key_quantity == "B.terminal.year") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_F_YEAR <- kqs |>
  #   dplyr::filter(key_quantity == "F.terminal.year") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_FTARGET <- kqs |>
  #   dplyr::filter(key_quantity == "F.target") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_FLIMIT <- kqs |>
  #   dplyr::filter(key_quantity == "F.limit") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_B_BEST <- kqs |>
  #   dplyr::filter(key_quantity == "B.terminal.est") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_F_BEST <- kqs |>
  #   dplyr::filter(key_quantity == "F.terminal.est") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_B_MIN <- kqs |>
  #   dplyr::filter(key_quantity == "B.terminal.min") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_B_MAX <- kqs |>
  #   dplyr::filter(key_quantity == "B.terminal.max") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_F_MIN <- kqs |>
  #   dplyr::filter(key_quantity == "F.terminal.min") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_F_MAX <- kqs |>
  #   dplyr::filter(key_quantity == "F.terminal.max") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_FMSY_MAX <- kqs |>
  #   dplyr::filter(key_quantity == "F.MSY.terminal.max") |>
  #   dplyr::select(value) |>
  #   as.numeric()
  # 
  # AS_FMSY_MIN <- kqs |>
  #   dplyr::filter(key_quantity == "F.MSY.terminal.min") |>
  #   dplyr::select(value) |>
  #   as.numeric()

  # insert values into the sis_assmt_template.csv file
  mapping <- tibble::tribble(
    ~key_quantity,          ~Variable,
    "landings.end.year",    "AS_LAST_DATA_YEAR",
    "F.MSY.terminal",       "AS_FMSY",
    "B.msy",                "AS_BMSY",
    "B.msy.min",            "AS_BMSY_MIN",
    "B.msy.max",            "AS_BMSY_MAX",
    "B.terminal.year",      "AS_B_YEAR",
    "F.terminal.year",      "AS_F_YEAR",
    "F.target",             "AS_FTARGET",
    "F.limit",              "AS_FLIMIT",
    "B.terminal.est",       "AS_B_BEST",
    "F.terminal.est",       "AS_F_BEST",
    "B.terminal.min",       "AS_B_MIN",
    "B.terminal.max",       "AS_B_MAX",
    "F.terminal.min",       "AS_F_MIN",
    "F.terminal.max",       "AS_F_MAX",
    "F.MSY.terminal.max",   "AS_FMSY_MAX",
    "F.MSY.terminal.min",   "AS_FMSY_MIN"
  )
  
  # Extract values and format into a key-value matching table
  new_vals <- kqs |> 
    dplyr::inner_join(mapping, by = "key_quantity") |> 
    dplyr::mutate(value = as.numeric(value)) |> 
    dplyr::select(Variable, new_value = value)
  
  # Update assmt_dat
  assmt_dat <- assmt_dat |> 
    dplyr::left_join(new_vals, by = "Variable") |> 
    dplyr::mutate(Value = ifelse(!is.na(new_value), new_value, Value)) |> 
    dplyr::select(-new_value)
  
  
  
  # At end: if assmt_dat$Value is NA and Default is 95, change it to Default
  for (i in seq_len(nrow(assmt_dat))) {
    if (is.na(assmt_dat$Value[i]) & assmt_dat$Default[i] == 95) {
      assmt_dat$Value[i] <- assmt_dat$Default[i]
    }
  }
  
}

# if existing copies are present, check user wants to overwrite values; OR just add new ones?


