#' Extract data from model results to send to SIS
#'
#' Semi-automate the extraction of key quantities from model results for eventual transmittance to SIS via `asar::export_to_sis()`.
#' 
#' @param sis_data_dir Path. Location of the existing sis_assmt_template.csv and sis_ts_template.csv files, or, if absent, where new versions of the files should be saved.
#' 
#' Default: The working directory.
#' 
#' @param kq_dir Path. Location of the existing key_quantities.csv file, or, if absent, where a new version of the file should be saved.
#' 
#' Default: The working directory.
#' 
#' @param model_results Filepath to the standardized, converted model output
#' .rda file generated with `stockplotr::convert_output()`. If provided, will be
#' used to generate figures and key quantities used to populate the SIS templates 
#' if key_quantities.csv does not exist.
#'
#' Default: NULL
#' 
#' @details This function acts within the following workflow:
#' 
#' 1. When a stock assessment is scheduled to conclude, SIS will generate an
#'  attachment or prompt containing metadata and identifiers.
#' 2. The user will open two csv files containing placeholders for all of the data required by SIS: sis_assmt_template.csv (assessment summary data) and sis_ts_template.csv (time series data). There are three ways to obtain these files:
#' 2a. Generate the files by running `asar::create_blank_sis()`
#' 2b. Locate the files in the "report" folder generated by running `asar::create_template()`.
#' 2c. Run `stockplotr::extract_sis_data()`, which will populate the templates with data originating from a converted model results file.
#' 3. The user will add the remaining necessary data into the csv files, ensuring that all required fields are completed.
#' 4. Run `export_to_sis()`, which will format and upload this data to a specific Google Drive folder.
#' 5. The uploaded contents will be resubmitted to SIS to finalize the record.
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' extract_sis_data(
#'   sis_data_dir = getwd()
#' )
#' }
#'
extract_sis_data <- function(sis_data_dir = getwd(),
                             key_quantities_dir = getwd(),
                             model_results = NULL
                             ) {
  # Check if existing data files exist; if not, start from blank templates
  if (!exists(fs::path(sis_data_dir, "sis_assmt_template.csv"))) {
    assmt_dat <- read.csv(fs::path("inst/resources/sis_assmt_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("No existing sis_assmt_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    assmt_dat <- read.csv(fs::path(sis_data_dir, "sis_assmt_template.csv"), stringsAsFactors = FALSE)
        cli::cli_alert_info("Found existing sis_assmt_template.csv in {sis_data_dir}.")
  }
  
  if (!exists(fs::path(sis_data_dir, "sis_ts_template.csv"))) {
    ts_dat <- read.csv(fs::path("inst/resources/sis_ts_template.csv"), stringsAsFactors = FALSE) 
    cli::cli_alert_info("No existing sis_ts_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    ts_dat <- read.csv(fs::path(sis_data_dir, "sis_ts_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("Found existing sis_ts_template.csv in {sis_data_dir}.")
  }
  
  # extract key quantities from csv and assign to variables
  kqs_path <- fs::path(key_quantities_dir, "key_quantities.csv")
  if (exists(kqs_path)){
    kqs <- read.csv(fs::path(key_quantities_dir,
                           "key_quantities.csv"), 
                  stringsAsFactors = FALSE)
    cli::cli_alert_info("Found existing key_quantities.csv in {key_quantities_dir}.")
  } else {
    cli::cli_alert_warning("No existing key_quantities.csv found in {key_quantities_dir}.")
    cli::cli_alert_info("To obtain key quantities, run the following functions and specify `make_rda = TRUE`:")
    cli::cli_bullets(c(
      "*" = "plot_fishing_mortality()",
      "*" = "plot_biomass()",
      "*" = "plot_landings()"
    ))
    
    # make_rdas_q <- readline("Do you want to create these plots now? (Y/N)")
    # 
    # if (!interactive()) {make_rdas_q <- "n"}
    # if (regexpr(make_rdas_q, "n", ignore.case = TRUE) == 1) {
    #   cli::cli_alert_danger("Fishing mortality, biomass, and landings plots will not be created.")
    # } else if (regexpr(make_rdas_q, "y", ignore.case = TRUE) == 1) {
    #   if (is.null(model_results)) {
    #     cli::cli_alert_danger("No model results file provided. Plots will not be created.")
    #   }
    #   cli::cli_alert_info("Creating plots:")
    #   
    #   load(model_results)
    #   
    #   cli::cli_alert_info("  * Fishing mortality")
    #   plot_fishing_mortality(dat = out_new,
    #                          make_rda = TRUE)
    #   
    #   cli::cli_alert_info("  * Biomass")
    #   plot_biomass(dat = out_new,
    #                make_rda = TRUE)
    #   
    #   cli::cli_alert_info("  * Landings")
    #   plot_landings(dat = out_new,
    #                 make_rda = TRUE)
    #   
    #   cli::cli_alert_success("Plots created.")
    # } else {
    #   cli::cli_alert_danger("Invalid input. Plots will not be created.")
    # }
  }
  
  if (exists(kqs_path)){
    # insert values into the sis_assmt_template.csv file
    mapping <- tibble::tribble(
      ~key_quantity,          ~Variable,
      "landings.end.year",    "AS_LAST_DATA_YEAR",
      "F.MSY.terminal",       "AS_FMSY",
      "B.msy",                "AS_BMSY",
      "B.msy.min",            "AS_BMSY_MIN",
      "B.msy.max",            "AS_BMSY_MAX",
      "B.terminal.year",      "AS_B_YEAR",
      "F.terminal.year",      "AS_F_YEAR",
      "F.target",             "AS_FTARGET",
      "F.limit",              "AS_FLIMIT",
      "B.terminal.est",       "AS_B_BEST",
      "F.terminal.est",       "AS_F_BEST",
      "B.terminal.min",       "AS_B_MIN",
      "B.terminal.max",       "AS_B_MAX",
      "F.terminal.min",       "AS_F_MIN",
      "F.terminal.max",       "AS_F_MAX",
      "F.MSY.terminal.max",   "AS_FMSY_MAX",
      "F.MSY.terminal.min",   "AS_FMSY_MIN"
    )
    
    # Extract values and format into a key-value matching table
    new_vals <- kqs |> 
      dplyr::inner_join(mapping, by = "key_quantity") |> 
      dplyr::mutate(value = as.numeric(value)) |> 
      dplyr::select(Variable, new_value = value)
    
    # Update assmt_dat
    assmt_dat <- assmt_dat |> 
      dplyr::left_join(new_vals, by = "Variable") |> 
      dplyr::mutate(Value = ifelse(!is.na(new_value), new_value, Value)) |> 
      dplyr::select(-new_value)
  }
  
  # obtain time series data
  
  
  
  # At end: if assmt_dat$Value is NA and Default is 95, change it to Default
  for (i in seq_len(nrow(assmt_dat))) {
    if (is.na(assmt_dat$Value[i]) & assmt_dat$Default[i] == 95) {
      assmt_dat$Value[i] <- assmt_dat$Default[i]
    }
  }
  
}

# if existing copies are present, check user wants to overwrite values; OR just add new ones?


