#' Extract data from model results to send to SIS
#'
#' Semi-automate the extraction of key quantities from model results for eventual transmittance to SIS via `asar::export_to_sis()`.
#' 
#' @param sis_data_dir Path. Location of the existing sis_assmt_template.csv and sis_ts_template.csv files, or, if absent, where new versions of the files should be saved.
#' 
#' Default: The working directory.
#' 
#' @param kq_dir Path. Location of the existing key_quantities.csv file, or, if absent, where a new version of the file should be saved.
#' 
#' Default: The working directory.
#' 
#' 
#' @param figures_tables_dir Path. Location of the existing 'figures' and 'tables' directories.
#' 
#' Default: The working directory.
#' 
#' @details This function acts within the following workflow:
#' 
#' 1. When a stock assessment is scheduled to conclude, SIS will generate an
#'  attachment or prompt containing metadata and identifiers.
#' 2. The user will open two csv files containing placeholders for all of the data required by SIS: sis_assmt_template.csv (assessment summary data) and sis_ts_template.csv (time series data). There are three ways to obtain these files:
#' 2a. Generate the files by running `asar::create_blank_sis()`
#' 2b. Locate the files in the "report" folder generated by running `asar::create_template()`.
#' 2c. Run `stockplotr::extract_sis_data()`, which will populate the templates with data originating from a converted model results file.
#' 3. The user will add the remaining necessary data into the csv files, ensuring that all required fields are completed.
#' 4. Run `export_to_sis()`, which will format and upload this data to a specific Google Drive folder.
#' 5. The uploaded contents will be resubmitted to SIS to finalize the record.
#' 
#' @export
#'
#' @examples
#' \dontrun{
#' extract_sis_data(
#'   sis_data_dir = getwd()
#' )
#' }
#'
extract_sis_data <- function(sis_data_dir = getwd(),
                             key_quantities_dir = getwd(),
                             figures_tables_dir = getwd()
                             ) {
  # Check if existing data files exist; if not, start from blank templates
  if (!file.exists(fs::path(sis_data_dir, "sis_assmt_template.csv"))) {
    assmt_dat <- read.csv(fs::path("inst/resources/sis_assmt_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("No existing sis_assmt_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    assmt_dat <- read.csv(fs::path(sis_data_dir, "sis_assmt_template.csv"), stringsAsFactors = FALSE)
        cli::cli_alert_info("Found existing sis_assmt_template.csv in {sis_data_dir}.")
  }
  
  if (!file.exists(fs::path(sis_data_dir, "sis_ts_template.csv"))) {
    ts_dat <- read.csv(fs::path("inst/resources/sis_ts_template.csv"), stringsAsFactors = FALSE) 
    cli::cli_alert_info("No existing sis_ts_template.csv found in {sis_data_dir}. Using blank template.")
  } else {
    ts_dat <- read.csv(fs::path(sis_data_dir, "sis_ts_template.csv"), stringsAsFactors = FALSE)
    cli::cli_alert_info("Found existing sis_ts_template.csv in {sis_data_dir}.")
  }
  
  # extract key quantities from csv and assign to variables
  kqs_path <- fs::path(key_quantities_dir, "key_quantities.csv")
  if (file.exists(kqs_path)){
    kqs <- read.csv(fs::path(key_quantities_dir,
                           "key_quantities.csv"), 
                  stringsAsFactors = FALSE)
    cli::cli_alert_info("Found existing key_quantities.csv in {key_quantities_dir}.")
  } else {
    cli::cli_alert_warning("No existing key_quantities.csv found in {key_quantities_dir}.")
    cli::cli_alert_info("To obtain key quantities relevant to the sis_assmt_template.csv, run the following functions and specify `make_rda = TRUE`:")
    cli::cli_bullets(c(
      "*" = "plot_fishing_mortality()",
      "*" = "plot_biomass()",
      "*" = "plot_landings()"
    ))
  }
  
  if (file.exists(kqs_path)){
    # insert values into the sis_assmt_template.csv file
    mapping <- tibble::tribble(
      ~key_quantity,          ~Variable,
      "landings.end.year",    "AS_LAST_DATA_YEAR",
      "F.MSY.terminal",       "AS_FMSY",
      "B.msy",                "AS_BMSY",
      "B.msy.min",            "AS_BMSY_MIN",
      "B.msy.max",            "AS_BMSY_MAX",
      "B.terminal.year",      "AS_B_YEAR",
      "F.terminal.year",      "AS_F_YEAR",
      "F.target",             "AS_FTARGET",
      "F.limit",              "AS_FLIMIT",
      "B.terminal.est",       "AS_B_BEST",
      "F.terminal.est",       "AS_F_BEST",
      "B.terminal.min",       "AS_B_MIN",
      "B.terminal.max",       "AS_B_MAX",
      "F.terminal.min",       "AS_F_MIN",
      "F.terminal.max",       "AS_F_MAX",
      "F.MSY.terminal.max",   "AS_FMSY_MAX",
      "F.MSY.terminal.min",   "AS_FMSY_MIN"
    )
    
    # Extract values and format into a key-value matching table
    new_vals <- kqs |> 
      dplyr::inner_join(mapping, by = "key_quantity") |> 
      dplyr::mutate(value = as.numeric(value)) |> 
      dplyr::select(Variable, new_value = value)
    
    # Update assmt_dat
    assmt_dat <- assmt_dat |> 
      dplyr::left_join(new_vals, by = "Variable") |> 
      dplyr::mutate(Value = ifelse(!is.na(new_value), new_value, Value)) |> 
      dplyr::select(-new_value)
  }
  
  # obtain time series data
  if (!dir.exists(fs::path(figures_tables_dir, "figures"))) {
    cli::cli_alert_info("'figures' folder not found in {sis_data_dir}.")
    cli::cli_alert_danger("Some time series data will not be extracted.")
  } else {
    fig_ts <- TRUE
    # ABUNDANCE
    tryCatch(
      {
        load(fs::path(figures_tables_dir, "figures", "abundance_at_age_figure.rda"))
        aaa <- rda[["figure"]][["layers"]][["geom_line"]]$data
        abundance <- aaa |>
          dplyr::group_by(year) |>
          dplyr::summarise(sum = sum(total_fish)) |>
          dplyr::rename(Abundance = sum)
      },
      error = function(e) {
        cli::cli_alert_warning("The 'abundance_at_age_figure.rda' file was not found in the figures folder. Abundance data will not be extracted.")
        abundance <<- NULL
      }
    )
    
    # SPAWNERS
    tryCatch({
      load(fs::path(figures_tables_dir, "figures", "spawning_biomass_figure.rda"))
      sb <- rda[["figure"]][["layers"]][["geom_line"]]$data
      spawning_biomass <- sb |>
        dplyr::group_by(year) |>
        dplyr::summarise(sum = sum(estimate)) |>
        dplyr::rename(Spawners = sum)
    },
    error = function(e) {
      cli::cli_alert_warning("The 'spawning_biomass_figure.rda' file was not found in the figures folder. Spawning biomass data will not be extracted.")
      spawning_biomass <<- NULL
    }
    )
    
    # RECRUITMENT
    tryCatch({
      load(fs::path(figures_tables_dir, "figures", "recruitment_figure.rda"))
      rec <- rda[["figure"]][["layers"]][["geom_line"]]$data
      recruitment <- rec |>
        dplyr::group_by(year) |>
        dplyr::summarise(sum = sum(predicted_recruitment)) |>
        dplyr::rename(Recruitment = sum)
    },
    error = function(e) {
      cli::cli_alert_warning("The 'recruitment_figure.rda' file was not found in the figures folder. Recruitment data will not be extracted.")
      recruitment <<- NULL
    })
    
    # FISHING MORTALITY
    tryCatch({
      load(fs::path(figures_tables_dir, "figures", "fishing_mortality_figure.rda"))
      fm <- rda[["figure"]][["layers"]][["geom_line"]]$data
      fishing_mortality <- fm |>
        dplyr::group_by(year) |>
        dplyr::summarise(mean = mean(estimate)) |>
        dplyr::rename(Fmort = mean)
    },
    error = function(e) {
      cli::cli_alert_warning("The 'fishing_mortality_figure.rda' file was not found in the figures folder. Fishing mortality data will not be extracted.")
      fishing_mortality <<- NULL
    })
    
    # INDEX
    tryCatch({
      load(fs::path(figures_tables_dir, "figures", "index_figure.rda"))
      index <- rda[["figure"]][["layers"]][["geom_line"]]$data
      index <- index |>
        dplyr::group_by(year) |>
        dplyr::summarise(mean = mean(estimate)) |>
        dplyr::rename(Index = mean)
    },
    error = function(e) {
      cli::cli_alert_warning("The 'index_figure.rda' file was not found in the figures folder. Index data will not be extracted.")
      index <<- NULL
    })
  }
  if (!dir.exists(fs::path(figures_tables_dir, "tables"))) {
    cli::cli_alert_info("'tables' folder not found in {sis_data_dir}.")
    cli::cli_alert_danger("Some time series data will not be extracted.")
  } else {
    table_ts <- TRUE
    #tryCatch(
      #{
        #TODO: update this once catch table released
      #   load(fs::path(figures_tables_dir, "tables", "catch_table.rda"))
      #   catch <- rda[["figure"]][["layers"]][["geom_line"]]$data
      #   catch <- aaa |>
      #     dplyr::group_by(year) |>
      #     dplyr::summarise(sum = sum(total_fish)) |>
      #     dplyr::rename(abundance = sum)
      # },
      # error = function(e) {
      #   cli::cli_alert_warning("The 'catch_table.rda' file was not found in the figures folder. Catch data will not be extracted.")
      #   catch <<- NULL
      # }
    #)
  }
  
  if(exists("fig_ts")){
    summaries <- c("abundance", "spawning_biomass", "recruitment", "fishing_mortality", "index")
    
    # join all summaries by year
    all_summaries <- c()
    for (i in seq_along(summaries)) {
      if (i == 1) {
        all_summaries <- get(summaries[i])
      } else {
        all_summaries <- dplyr::full_join(all_summaries,
                                          get(summaries[i]),
                                          by = "year")
      }
    }
  }
  if (exists("table_ts") & exists("catch")){
    if (exists("all_summaries")){
      all_summaries <- dplyr::full_join(all_summaries,
                                      get("catch"),
                                      by = "year")
      summaries <- c(summaries, "catch")
    } else {
      all_summaries <- get("catch")
    }
  }
  
  ts_options <- summaries[!is.na(summaries)]
  
  if (length(ts_options) > 1){
    cli::cli_alert_info("Multiple time series summaries were extracted: {ts_options}.")
    primary <- readline("Which category should be designated as the Primary time series?")
    
    if (!interactive()) {
      primary <- "abundance"
      cli::cli_alert_info("Primary category set to 'abundance' by default in non-interactive mode.")
    }
    if (primary %notin% ts_options) {
      cli::cli_abort("Invalid primary category specified. Please choose from: {ts_options}.")
    }
  } else if (length(ts_options) == 1) {
    primary <- ts_options
    cli::cli_alert_info("Only one time series summary was extracted ({primary}) and will be used as the Primary time series.")
  } else {
    cli::cli_abort("No time series summaries were extracted. Please check the figures and tables directories.")
  }
  
  # TODO: add all_summaries to ts_dat, matching by year and variable name
  test <- all_summaries |>
    dplyr::rename("Year" = "year") |>
    tidyr::pivot_longer(cols = -Year, names_to = "Category", values_to = "Value") |>
    dplyr::mutate(Primary = ifelse(tolower(Category) == primary, "Y", ""))
  
  # At end: if assmt_dat$Value is NA and Default is 95, change it to Default
  for (i in seq_len(nrow(assmt_dat))) {
    if (is.na(assmt_dat$Value[i]) & assmt_dat$Default[i] == 95) {
      assmt_dat$Value[i] <- assmt_dat$Default[i]
    }
  }
  #TODO: show an example of a filled-out template
}

# if existing copies are present, check user wants to overwrite values; OR just add new ones?


